import numpy as np
from PIL import Image
import io


def export_png(heightmap: np.ndarray) -> io.BytesIO:
    img = Image.fromarray((np.clip(heightmap, 0, 1) * 255).astype(np.uint8))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf


def export_obj(
    heightmap: np.ndarray,
    resolution: int = 128,
    width_mm: float = 150.0,
    height_mm: float = 150.0,
    max_depth_mm: float = 30.0,
) -> io.BytesIO:
    """Triangulated mesh with physical dimensions (150×150×30 mm)."""
    pil = Image.fromarray((np.clip(heightmap, 0, 1) * 255).astype(np.uint8))
    pil = pil.resize((resolution, resolution), Image.LANCZOS)
    hmap = np.array(pil, dtype=np.float32) / 255.0

    H, W = hmap.shape
    lines = [
        f"# Clay tile OBJ — {width_mm}mm × {height_mm}mm × {max_depth_mm}mm",
        "# Generated by CLAY-CREATE pipeline",
        "",
    ]

    for row in range(H):
        for col in range(W):
            x = col / (W - 1) * width_mm
            y = (H - 1 - row) / (H - 1) * height_mm
            z = hmap[row, col] * max_depth_mm
            lines.append(f"v {x:.3f} {y:.3f} {z:.3f}")

    lines.append("")

    for row in range(H - 1):
        for col in range(W - 1):
            i00 = row * W + col + 1          # OBJ is 1-indexed
            i10 = row * W + col + 2
            i01 = (row + 1) * W + col + 1
            i11 = (row + 1) * W + col + 2
            lines.append(f"f {i00} {i10} {i11}")
            lines.append(f"f {i00} {i11} {i01}")

    buf = io.BytesIO("\n".join(lines).encode())
    buf.seek(0)
    return buf
